version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/tiendita-api
      # - static-content:/portfolio/static
    ports:
      - "8000:8000"
    env_file: 
      - .env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
   build: ./nginx
   volumes:
     - static-content:/static
   ports:
     - "80:80"
   depends_on:
     - web 
volumes:
  static-content:
  